ALTER TABLE "customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customer_memories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customer_note_images" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customer_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customer_note_advice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "staffs" ENABLE ROW LEVEL SECURITY;
